/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/oam-dev/oam-go-sdk/apis/core.oam.dev/v1alpha1"
	scheme "github.com/oam-dev/oam-go-sdk/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TraitsGetter has a method to return a TraitInterface.
// A group's client should implement this interface.
type TraitsGetter interface {
	Traits(namespace string) TraitInterface
}

// TraitInterface has methods to work with Trait resources.
type TraitInterface interface {
	Create(*v1alpha1.Trait) (*v1alpha1.Trait, error)
	Update(*v1alpha1.Trait) (*v1alpha1.Trait, error)
	UpdateStatus(*v1alpha1.Trait) (*v1alpha1.Trait, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Trait, error)
	List(opts v1.ListOptions) (*v1alpha1.TraitList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Trait, err error)
	TraitExpansion
}

// traits implements TraitInterface
type traits struct {
	client rest.Interface
	ns     string
}

// newTraits returns a Traits
func newTraits(c *CoreV1alpha1Client, namespace string) *traits {
	return &traits{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trait, and returns the corresponding trait object, and an error if there is any.
func (c *traits) Get(name string, options v1.GetOptions) (result *v1alpha1.Trait, err error) {
	result = &v1alpha1.Trait{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("traits").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Traits that match those selectors.
func (c *traits) List(opts v1.ListOptions) (result *v1alpha1.TraitList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TraitList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("traits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested traits.
func (c *traits) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("traits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a trait and creates it.  Returns the server's representation of the trait, and an error, if there is any.
func (c *traits) Create(trait *v1alpha1.Trait) (result *v1alpha1.Trait, err error) {
	result = &v1alpha1.Trait{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("traits").
		Body(trait).
		Do().
		Into(result)
	return
}

// Update takes the representation of a trait and updates it. Returns the server's representation of the trait, and an error, if there is any.
func (c *traits) Update(trait *v1alpha1.Trait) (result *v1alpha1.Trait, err error) {
	result = &v1alpha1.Trait{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("traits").
		Name(trait.Name).
		Body(trait).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *traits) UpdateStatus(trait *v1alpha1.Trait) (result *v1alpha1.Trait, err error) {
	result = &v1alpha1.Trait{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("traits").
		Name(trait.Name).
		SubResource("status").
		Body(trait).
		Do().
		Into(result)
	return
}

// Delete takes name of the trait and deletes it. Returns an error if one occurs.
func (c *traits) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("traits").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *traits) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("traits").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched trait.
func (c *traits) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Trait, err error) {
	result = &v1alpha1.Trait{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("traits").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
