/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ApplicationConfigurationListerExpansion allows custom methods to be added to
// ApplicationConfigurationLister.
type ApplicationConfigurationListerExpansion interface{}

// ApplicationConfigurationNamespaceListerExpansion allows custom methods to be added to
// ApplicationConfigurationNamespaceLister.
type ApplicationConfigurationNamespaceListerExpansion interface{}

// ApplicationScopeListerExpansion allows custom methods to be added to
// ApplicationScopeLister.
type ApplicationScopeListerExpansion interface{}

// ApplicationScopeNamespaceListerExpansion allows custom methods to be added to
// ApplicationScopeNamespaceLister.
type ApplicationScopeNamespaceListerExpansion interface{}

// ComponentSchematicListerExpansion allows custom methods to be added to
// ComponentSchematicLister.
type ComponentSchematicListerExpansion interface{}

// ComponentSchematicNamespaceListerExpansion allows custom methods to be added to
// ComponentSchematicNamespaceLister.
type ComponentSchematicNamespaceListerExpansion interface{}

// TraitListerExpansion allows custom methods to be added to
// TraitLister.
type TraitListerExpansion interface{}

// TraitNamespaceListerExpansion allows custom methods to be added to
// TraitNamespaceLister.
type TraitNamespaceListerExpansion interface{}
