/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/oam-dev/oam-go-sdk/apis/core.oam.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTraits implements TraitInterface
type FakeTraits struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var traitsResource = schema.GroupVersionResource{Group: "core.oam.dev", Version: "v1alpha1", Resource: "traits"}

var traitsKind = schema.GroupVersionKind{Group: "core.oam.dev", Version: "v1alpha1", Kind: "Trait"}

// Get takes name of the trait, and returns the corresponding trait object, and an error if there is any.
func (c *FakeTraits) Get(name string, options v1.GetOptions) (result *v1alpha1.Trait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(traitsResource, c.ns, name), &v1alpha1.Trait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Trait), err
}

// List takes label and field selectors, and returns the list of Traits that match those selectors.
func (c *FakeTraits) List(opts v1.ListOptions) (result *v1alpha1.TraitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(traitsResource, traitsKind, c.ns, opts), &v1alpha1.TraitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TraitList{ListMeta: obj.(*v1alpha1.TraitList).ListMeta}
	for _, item := range obj.(*v1alpha1.TraitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested traits.
func (c *FakeTraits) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(traitsResource, c.ns, opts))

}

// Create takes the representation of a trait and creates it.  Returns the server's representation of the trait, and an error, if there is any.
func (c *FakeTraits) Create(trait *v1alpha1.Trait) (result *v1alpha1.Trait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(traitsResource, c.ns, trait), &v1alpha1.Trait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Trait), err
}

// Update takes the representation of a trait and updates it. Returns the server's representation of the trait, and an error, if there is any.
func (c *FakeTraits) Update(trait *v1alpha1.Trait) (result *v1alpha1.Trait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(traitsResource, c.ns, trait), &v1alpha1.Trait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Trait), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTraits) UpdateStatus(trait *v1alpha1.Trait) (*v1alpha1.Trait, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(traitsResource, "status", c.ns, trait), &v1alpha1.Trait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Trait), err
}

// Delete takes name of the trait and deletes it. Returns an error if one occurs.
func (c *FakeTraits) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(traitsResource, c.ns, name), &v1alpha1.Trait{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTraits) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(traitsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TraitList{})
	return err
}

// Patch applies the patch and returns the patched trait.
func (c *FakeTraits) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Trait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(traitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Trait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Trait), err
}
